//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRentalPOS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.VehicleRentals = new HashSet<VehicleRental>();
        }
    
        public int Id { get; set; }
        public int VehicleModelId { get; set; }
        public string Color { get; set; }
        public short Year { get; set; }
        public string LicensePlate { get; set; }
        public bool DeleteFlag { get; set; }
        public string VIN { get; set; }
    
        public virtual VehicleModel VehicleModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleRental> VehicleRentals { get; set; }
    }
}
